/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthAccountRouteImport } from './routes/_auth/account'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as FoldersIndexRouteImport } from './routes/folders/index'
import { Route as FoldersLibraryRouteImport } from './routes/folders/$library'
import { Route as IssuesIndexRouteImport } from './routes/issues/index'
import { Route as IssuesLibraryRouteImport } from './routes/issues/$library'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as FoldersLibraryElementRouteImport } from './routes/folders/$library_.$element'
import { Route as IssuesLibraryElementRouteImport } from './routes/issues/$library_.$element'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const FoldersIndexRoute = FoldersIndexRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersLibraryRoute = FoldersLibraryRouteImport.update({
  id: '/folders/$library',
  path: '/folders/$library',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesLibraryRoute = IssuesLibraryRouteImport.update({
  id: '/issues/$library',
  path: '/issues/$library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersLibraryElementRoute = FoldersLibraryElementRouteImport.update({
  id: '/folders/$library_/$element',
  path: '/folders/$library/$element',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesLibraryElementRoute = IssuesLibraryElementRouteImport.update({
  id: '/issues/$library_/$element',
  path: '/issues/$library/$element',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AuthAccountRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/folders/$library': typeof FoldersLibraryRoute
  '/issues/$library': typeof IssuesLibraryRoute
  '/folders/': typeof FoldersIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/folders/$library/$element': typeof FoldersLibraryElementRoute
  '/issues/$library/$element': typeof IssuesLibraryElementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AuthAccountRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/folders/$library': typeof FoldersLibraryRoute
  '/issues/$library': typeof IssuesLibraryRoute
  '/folders': typeof FoldersIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/folders/$library/$element': typeof FoldersLibraryElementRoute
  '/issues/$library/$element': typeof IssuesLibraryElementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/account': typeof AuthAccountRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/folders/$library': typeof FoldersLibraryRoute
  '/issues/$library': typeof IssuesLibraryRoute
  '/folders/': typeof FoldersIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/folders/$library_/$element': typeof FoldersLibraryElementRoute
  '/issues/$library_/$element': typeof IssuesLibraryElementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/signup'
    | '/folders/$library'
    | '/issues/$library'
    | '/folders/'
    | '/issues/'
    | '/api/auth/$'
    | '/folders/$library/$element'
    | '/issues/$library/$element'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/signup'
    | '/folders/$library'
    | '/issues/$library'
    | '/folders'
    | '/issues'
    | '/api/auth/$'
    | '/folders/$library/$element'
    | '/issues/$library/$element'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/account'
    | '/_guest/login'
    | '/_guest/signup'
    | '/folders/$library'
    | '/issues/$library'
    | '/folders/'
    | '/issues/'
    | '/api/auth/$'
    | '/folders/$library_/$element'
    | '/issues/$library_/$element'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  FoldersLibraryRoute: typeof FoldersLibraryRoute
  IssuesLibraryRoute: typeof IssuesLibraryRoute
  FoldersIndexRoute: typeof FoldersIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  FoldersLibraryElementRoute: typeof FoldersLibraryElementRoute
  IssuesLibraryElementRoute: typeof IssuesLibraryElementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/folders/': {
      id: '/folders/'
      path: '/folders'
      fullPath: '/folders/'
      preLoaderRoute: typeof FoldersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$library': {
      id: '/folders/$library'
      path: '/folders/$library'
      fullPath: '/folders/$library'
      preLoaderRoute: typeof FoldersLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$library': {
      id: '/issues/$library'
      path: '/issues/$library'
      fullPath: '/issues/$library'
      preLoaderRoute: typeof IssuesLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$library_/$element': {
      id: '/folders/$library_/$element'
      path: '/folders/$library/$element'
      fullPath: '/folders/$library/$element'
      preLoaderRoute: typeof FoldersLibraryElementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$library_/$element': {
      id: '/issues/$library_/$element'
      path: '/issues/$library/$element'
      fullPath: '/issues/$library/$element'
      preLoaderRoute: typeof IssuesLibraryElementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAccountRoute: typeof AuthAccountRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccountRoute: AuthAccountRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  FoldersLibraryRoute: FoldersLibraryRoute,
  IssuesLibraryRoute: IssuesLibraryRoute,
  FoldersIndexRoute: FoldersIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  FoldersLibraryElementRoute: FoldersLibraryElementRoute,
  IssuesLibraryElementRoute: IssuesLibraryElementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
