/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthMeRouteRouteImport } from './routes/_auth/me/route'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard/route'
import { Route as AuthContractsRouteRouteImport } from './routes/_auth/contracts/route'
import { Route as AuthAccessDeniedRouteRouteImport } from './routes/_auth/access-denied/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAdminRouterRouteImport } from './routes/_auth/_admin/router'
import { Route as AuthRatesDevelopersRouteRouteImport } from './routes/_auth/rates/developers/route'
import { Route as AuthRatesDesignersRouteRouteImport } from './routes/_auth/rates/designers/route'
import { Route as AuthAdminInvoicesRouteRouteImport } from './routes/_auth/_admin/invoices/route'
import { Route as AuthContractsEmploymentsPermanentRouteRouteImport } from './routes/_auth/contracts/employments/permanent/route'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMeRouteRoute = AuthMeRouteRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthContractsRouteRoute = AuthContractsRouteRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAccessDeniedRouteRoute = AuthAccessDeniedRouteRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRouterRoute = AuthAdminRouterRouteImport.update({
  id: '/_admin/router',
  path: '/router',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRatesDevelopersRouteRoute =
  AuthRatesDevelopersRouteRouteImport.update({
    id: '/rates/developers',
    path: '/rates/developers',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthRatesDesignersRouteRoute = AuthRatesDesignersRouteRouteImport.update({
  id: '/rates/designers',
  path: '/rates/designers',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminInvoicesRouteRoute = AuthAdminInvoicesRouteRouteImport.update({
  id: '/_admin/invoices',
  path: '/invoices',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthContractsEmploymentsPermanentRouteRoute =
  AuthContractsEmploymentsPermanentRouteRouteImport.update({
    id: '/employments/permanent',
    path: '/employments/permanent',
    getParentRoute: () => AuthContractsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AuthAccessDeniedRouteRoute
  '/contracts': typeof AuthContractsRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRouteRoute
  '/me': typeof AuthMeRouteRoute
  '/invoices': typeof AuthAdminInvoicesRouteRoute
  '/rates/designers': typeof AuthRatesDesignersRouteRoute
  '/rates/developers': typeof AuthRatesDevelopersRouteRoute
  '/router': typeof AuthAdminRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/contracts/employments/permanent': typeof AuthContractsEmploymentsPermanentRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AuthAccessDeniedRouteRoute
  '/contracts': typeof AuthContractsRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRouteRoute
  '/me': typeof AuthMeRouteRoute
  '/invoices': typeof AuthAdminInvoicesRouteRoute
  '/rates/designers': typeof AuthRatesDesignersRouteRoute
  '/rates/developers': typeof AuthRatesDevelopersRouteRoute
  '/router': typeof AuthAdminRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/contracts/employments/permanent': typeof AuthContractsEmploymentsPermanentRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/access-denied': typeof AuthAccessDeniedRouteRoute
  '/_auth/contracts': typeof AuthContractsRouteRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRouteRoute
  '/_auth/me': typeof AuthMeRouteRoute
  '/_auth/_admin/invoices': typeof AuthAdminInvoicesRouteRoute
  '/_auth/rates/designers': typeof AuthRatesDesignersRouteRoute
  '/_auth/rates/developers': typeof AuthRatesDevelopersRouteRoute
  '/_auth/_admin/router': typeof AuthAdminRouterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/contracts/employments/permanent': typeof AuthContractsEmploymentsPermanentRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/contracts'
    | '/dashboard'
    | '/me'
    | '/invoices'
    | '/rates/designers'
    | '/rates/developers'
    | '/router'
    | '/api/auth/$'
    | '/contracts/employments/permanent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/contracts'
    | '/dashboard'
    | '/me'
    | '/invoices'
    | '/rates/designers'
    | '/rates/developers'
    | '/router'
    | '/api/auth/$'
    | '/contracts/employments/permanent'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/access-denied'
    | '/_auth/contracts'
    | '/_auth/dashboard'
    | '/_auth/me'
    | '/_auth/_admin/invoices'
    | '/_auth/rates/designers'
    | '/_auth/rates/developers'
    | '/_auth/_admin/router'
    | '/api/auth/$'
    | '/_auth/contracts/employments/permanent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/me': {
      id: '/_auth/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthMeRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/contracts': {
      id: '/_auth/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthContractsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/access-denied': {
      id: '/_auth/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AuthAccessDeniedRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_admin/router': {
      id: '/_auth/_admin/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof AuthAdminRouterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/rates/developers': {
      id: '/_auth/rates/developers'
      path: '/rates/developers'
      fullPath: '/rates/developers'
      preLoaderRoute: typeof AuthRatesDevelopersRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/rates/designers': {
      id: '/_auth/rates/designers'
      path: '/rates/designers'
      fullPath: '/rates/designers'
      preLoaderRoute: typeof AuthRatesDesignersRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/_admin/invoices': {
      id: '/_auth/_admin/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthAdminInvoicesRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/contracts/employments/permanent': {
      id: '/_auth/contracts/employments/permanent'
      path: '/employments/permanent'
      fullPath: '/contracts/employments/permanent'
      preLoaderRoute: typeof AuthContractsEmploymentsPermanentRouteRouteImport
      parentRoute: typeof AuthContractsRouteRoute
    }
  }
}

interface AuthContractsRouteRouteChildren {
  AuthContractsEmploymentsPermanentRouteRoute: typeof AuthContractsEmploymentsPermanentRouteRoute
}

const AuthContractsRouteRouteChildren: AuthContractsRouteRouteChildren = {
  AuthContractsEmploymentsPermanentRouteRoute:
    AuthContractsEmploymentsPermanentRouteRoute,
}

const AuthContractsRouteRouteWithChildren =
  AuthContractsRouteRoute._addFileChildren(AuthContractsRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAccessDeniedRouteRoute: typeof AuthAccessDeniedRouteRoute
  AuthContractsRouteRoute: typeof AuthContractsRouteRouteWithChildren
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRoute
  AuthMeRouteRoute: typeof AuthMeRouteRoute
  AuthAdminInvoicesRouteRoute: typeof AuthAdminInvoicesRouteRoute
  AuthRatesDesignersRouteRoute: typeof AuthRatesDesignersRouteRoute
  AuthRatesDevelopersRouteRoute: typeof AuthRatesDevelopersRouteRoute
  AuthAdminRouterRoute: typeof AuthAdminRouterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccessDeniedRouteRoute: AuthAccessDeniedRouteRoute,
  AuthContractsRouteRoute: AuthContractsRouteRouteWithChildren,
  AuthDashboardRouteRoute: AuthDashboardRouteRoute,
  AuthMeRouteRoute: AuthMeRouteRoute,
  AuthAdminInvoicesRouteRoute: AuthAdminInvoicesRouteRoute,
  AuthRatesDesignersRouteRoute: AuthRatesDesignersRouteRoute,
  AuthRatesDevelopersRouteRoute: AuthRatesDevelopersRouteRoute,
  AuthAdminRouterRoute: AuthAdminRouterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
